# Generated by Django 4.0 on 2021-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_punch', '0002_resident_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='punch_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='floor',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='resident',
            name='title_tag',
            field=models.CharField(max_length=100),
        ),
    ]
