# Generated by Django 4.0 on 2021-12-28 23:26

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('resident_punch', '0003_punch_punch_in_alter_resident_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='title_tag',
        ),
        migrations.AlterField(
            model_name='counselor',
            name='floor',
            field=models.IntegerField(choices=[(5, 'Women'), (4, 'Four'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], default=4),
        ),
        migrations.AlterField(
            model_name='punch',
            name='time',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now(), verbose_name='Time of punch'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='floor',
            field=models.IntegerField(choices=[(5, 'Women'), (4, 'Four'), (6, 'Six'), (7, 'Seven'), (8, 'Eight')], default=4),
        ),
    ]
